name: LorenRoetman
favicon: null
layout_spectrum: 0.54907
typography_spectrum: 0.36443629022687674
title: Skiffy in Chief
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
