title: Skiffy in Chief
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0
favicon: null
name: LorenRoetman
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.8125
  lightness: 0
  saturation: 0.9333895
  rhythmicContrast: 0.75
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
typography_spectrum: 0.5876897
